### ISSUE TITLE
GitHub Actions: `save-always` does not work as intended

### ISSUE THREAD

**Issue by cclauss** [OCamlPro/gnucobol#196]
See `save-always` warnings at https://github.com/OCamlPro/gnucobol/actions/runs/11480929540 and other GitHub Actions.
> Input 'save-always' has been deprecated with message: save-always does not work as intended and will be removed in a future release. A separate `actions/cache/restore` step should be used instead. See https://github.com/actions/cache/tree/main/save#always-save-cache for more details.

**Comment by GitMensch** [comment]
Should this be solved with a PR automatically created after #195?
We may see that if you "enable" that on your repo (or a copy if the "fork" state does skip the creation of those).
