### ISSUE TITLE
recheck defaultbyte setting for GCOS

### ISSUE THREAD

**Issue by GitMensch** [OCamlPro/gnucobol#53]
Currently its setting is the GnuCOBOL default "initialize per PIC" https://github.com/OCamlPro/gnucobol/blob/1bd1290a83b5faca899b1b71d885dd5451e49d05/config/gcos-strict.conf#L263

Please recheck what the content of data that has no `VALUE` clause is at the start of procedure division, IBM seems to have hex null in those, MF and ACU have space.

**Comment by nberth** [comment]
The reference documentation explicitly states those are undefined. Yet, we could perform some tests to check whether an implementation behaves in a particular way.

**Comment by GitMensch** [comment]
Sounds reasonable as this helps for migrations ("same 'undefined' behavior").

Note: implementations actually _do_ have it undefined (and that's the note in the COBOL standard, too); GnuCOBOL currently does not have an option to be so. An implementation for it seems quite easy and would be very welcomed - in this case the codegen part that sets the variables to a value would just be skipped for anything without a value clause.
Given that many programs have huge `WORKING-STORAGE` / `LOCAL-STORAGE` the codegen for initialization can be _many_ pages of code, it gets less when the defaultbyte is set (because then all of those "undefined" are commonly zero/space) so a single memset can be used for each group that has no value clause in its sub-items and much less (no memset at all) if we get the "undefined" value in.
For `LOCAL-STORARE` (and for `INITIAL` programs also for `WORKING-STORAGE`) this init code is executed on each program invocation (and there were cases in the past were the init code led to many cpu-cycles to just get to the first statements afterwards which say "nothing to do - exit program").

**Comment by nberth** [comment]
Based on our tests on a GCOS system, it seems the behavior is similar to IBMs, with null bytes throughout.

If you wish I can do a dedicated PR for that, even though that'll be a very small one.

**Comment by GitMensch** [comment]
> Based on our tests on a GCOS system, it seems the behavior is similar to IBMs, with null bytes throughout.

Thanks for testing this. I guess you've also checked `MOVE SPACE TO fiel-with-no-value` in a sub-program, then cancel it, then call it again and check its data, already?

> If you wish I can do a dedicated PR for that, even though that'll be a very small one.

It would be enough to just commit that change upstream, ideally together with the same change in ibm.conf. Do both along with a config/Changelog entry, then run make check (NIST does not run with either of these stds, so there's no point in testing that), see if we need to adjust any testcase, if necessary do so, if not _consider_ to add one :-) to ensure this will be correct in the future, then commit.
